// Code generated by go-enum
// DO NOT EDIT!

package enums

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const (
	// ITunes is a LibraryType of type ITunes
	ITunes LibraryType = iota
	// PRIME is a LibraryType of type PRIME
	PRIME
	// File is a LibraryType of type File
	File
	// Traktor is a LibraryType of type Traktor
	Traktor
)

const _LibraryTypeName = "ITunesPRIMEFileTraktor"

var _LibraryTypeNames = []string{
	_LibraryTypeName[0:6],
	_LibraryTypeName[6:11],
	_LibraryTypeName[11:15],
	_LibraryTypeName[15:22],
}

// LibraryTypeNames returns a list of possible string values of LibraryType.
func LibraryTypeNames() []string {
	tmp := make([]string, len(_LibraryTypeNames))
	copy(tmp, _LibraryTypeNames)
	return tmp
}

var _LibraryTypeMap = map[LibraryType]string{
	0: _LibraryTypeName[0:6],
	1: _LibraryTypeName[6:11],
	2: _LibraryTypeName[11:15],
	3: _LibraryTypeName[15:22],
}

// String implements the Stringer interface.
func (x LibraryType) String() string {
	if str, ok := _LibraryTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("LibraryType(%d)", x)
}

var _LibraryTypeValue = map[string]LibraryType{
	_LibraryTypeName[0:6]:                    0,
	strings.ToLower(_LibraryTypeName[0:6]):   0,
	_LibraryTypeName[6:11]:                   1,
	strings.ToLower(_LibraryTypeName[6:11]):  1,
	_LibraryTypeName[11:15]:                  2,
	strings.ToLower(_LibraryTypeName[11:15]): 2,
	_LibraryTypeName[15:22]:                  3,
	strings.ToLower(_LibraryTypeName[15:22]): 3,
}

// ParseLibraryType attempts to convert a string to a LibraryType
func ParseLibraryType(name string) (LibraryType, error) {
	if x, ok := _LibraryTypeValue[name]; ok {
		return x, nil
	}
	return LibraryType(0), fmt.Errorf("%s is not a valid LibraryType, try [%s]", name, strings.Join(_LibraryTypeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x LibraryType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *LibraryType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseLibraryType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Scan implements the Scanner interface.
func (x *LibraryType) Scan(value interface{}) error {
	var name string

	switch v := value.(type) {
	case string:
		name = v
	case []byte:
		name = string(v)
	case nil:
		*x = LibraryType(0)
		return nil
	}

	tmp, err := ParseLibraryType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Value implements the driver Valuer interface.
func (x LibraryType) Value() (driver.Value, error) {
	return x.String(), nil
}
